### ISSUE TITLE
Practice data set links broken

### ISSUE THREAD

**Issue by cjfields** [h3abionet/H3ABionet-SOPs#11]
I noticed a number of the practice data set links are broken, likely from old URLs. Examples:

Variant calling: http://h3data.cbio.uct.ac.za/assessments/NextGenVariantCalling/practice/
16S: http://h3data.cbio.uct.ac.za/assessments/16SrRNADiversityAnalysis/practice

**Comment by cjfields** [comment]
Links appear to be fixed now.  Closing.

**Comment by MinBio** [comment]
still broken. unaccessible
